language: ruby
rvm:
    - 2.3.1
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
# uncomment this line if your project needs to run something other than `rake`:
# # # script: bundle exec rspec spec
